---
config:
  layout: elk
---
stateDiagram
  direction LR
  [*] --> Бездіяльність

  Бездіяльність --> Черга
  Черга --> Обчислення
  Обчислення --> Бездіяльність
  Обчислення --> Завершено

  Завершено --> [*]
