query Experiment($_id: ID!) {
  experiment(_id: $_id) {
    _id
    name
    description
    fileId
    status
    createdAt
    optimization {
      progress
      status
      bestPipelineId
      bestScore
      history {
        message
        status
        createdAt
      }
    }
    graph {
      _id
      computationMode
      experimentId
      createdAt
      settings {
        metrics {
          accuracy
          f1
          rocAuc
          ntps
        }
        queues
        folds
        hyperOptimizationMinutesPerPipeline
      }
      nodes {
        _id
        label
        stage
        technology
        type
        settings {
          key
          value
        }
        parentId
      }
    }
  }
}
