erDiagram
	direction TB

	"Експеримент" {
	
	}
		"Графова структура конвеєра програмних компонентів" {
		}

	"Конвеєр програмних компонентів" {
		string id
		string experimentId
		string graphId
		json nodeIds
		json computationResult
		string name
		datetime createdAt
		datetime updatedAt
	}

	"Вузол" {
	
	}

	"Графова структура конвеєра програмних компонентів" ||--o{ "Конвеєр програмних компонентів" : "Є основою для конвеєрів програмних компонентів"
	"Експеримент" ||--o{ "Конвеєр програмних компонентів" : "Містить конвеєри програмних компонентів"
	"Конвеєр програмних компонентів" }o--o{ "Вузол" : "Використовує вузли"
