---
config:
  layout: elk
---
stateDiagram
  direction LR
  [*] --> Створено
  Створено --> Налаштування
  Налаштування --> Обчислення
  Обчислення --> Оптимізація
  Оптимізація --> Завершено
  Завершено --> [*]а