mutation GenerateExperimentGraph($input: GenerateExperimentGraphInput!) {
  generateExperimentGraph(input: $input) {
    _id
    name
    description
    fileId
    status
    createdAt
    graph {
      _id
      experimentId
      createdAt
      settings {
        metrics {
          accuracy
          f1
          rocAuc
          ntps
        }
        queues
        folds
        hyperOptimizationMinutesPerPipeline
        predictDataPercent
      }
      nodes {
        _id
        label
        stage
        technology
        type
        settings {
          key
          value
        }
        parentId
      }
    }
  }
}
