mutation UpdateExperiment($input: UpdateExperimentInput!) {
  updateExperiment(input: $input) {
    id
    name
    description
    status
    runs
    fileName
    createdAt
    graph {
      id
      experimentId
      createdAt
      nodes {
        id
        label
        type
        children {
          id
          label
          type
          children {
            id
            label
            type
          }
        }
      }
      edges {
        id
        from
        to
      }
    }
  }
}
